### ISSUE TITLE
policy about purging personal information

### ISSUE THREAD

**Issue by vagrantc** [lamby/try.diffoscope.org#3]
The privacy policy says try.diffoscope.org keeps logs of personal information such as ip addresses, and the site says results are purged after 30 days.

Would it be plausible/desireable/acceptible to modify the behavior and policy to also purge personal information in some time period? Maybe also 30 days, to keep it consistant with the other results data?

live well,
  vagrant

**Comment by vagrantc** [comment]
Oh, the full context where these issues came up was submitting trydiffoscope for inclusion in GNU Guix:

https://issues.guix.info/issue/34449#4

Maybe that helps frame the questions a bit better.

**Comment by lamby** [comment]
There is no deliberate storage of IP addresses at all, that's only really there in the (copy-pasted, mind!) by accident and because I didn't think of it before. I believe we only store IP addresses in `nginx` access and error which could easily be scrubbed in < 30 days. Or indeed to not stored at all. Or anonymized with http://ipscrub.org/ or similar.

**Comment by lamby** [comment]
Moved to https://salsa.debian.org/reproducible-builds/try.diffoscope.org/issues/3
